print ("Lo que sea para mirar como hacer por lo menos una rama principal en github")
print("Hola Mundo")
print ("bueno nose porque no quedo el primer mensaje david del futuro pero son los mismo comandos que para java")
print ("Bueno metamos otra linea breves ")
print("pero que demonios")
